import { describe, expect, it } from 'vitest';
import { parseMapYaml, MapYamlParseError } from '../../src/lib/mapYaml';

describe('parseMapYaml — Track D scale fix', () => {
  it('parses a minimal valid ROS map_server YAML body', () => {
    const text =
      'image: studio_v1.pgm\n' +
      'resolution: 0.05\n' +
      'origin: [0.0, 0.0, 0.0]\n' +
      'occupied_thresh: 0.65\n' +
      'free_thresh: 0.196\n' +
      'negate: 0\n';
    const m = parseMapYaml(text);
    expect(m.image).toBe('studio_v1.pgm');
    expect(m.resolution).toBe(0.05);
    expect(m.origin).toEqual([0, 0, 0]);
    expect(m.negate).toBe(0);
  });

  it('throws on missing resolution', () => {
    const text = 'image: x.pgm\norigin: [0,0,0]\nnegate: 0\n';
    expect(() => parseMapYaml(text)).toThrow(MapYamlParseError);
    try {
      parseMapYaml(text);
    } catch (e) {
      expect((e as MapYamlParseError).reason).toBe('missing_resolution');
    }
  });

  it('throws on non-numeric resolution', () => {
    const text = 'image: x.pgm\nresolution: abc\norigin: [0,0,0]\n';
    expect(() => parseMapYaml(text)).toThrow(MapYamlParseError);
    try {
      parseMapYaml(text);
    } catch (e) {
      expect((e as MapYamlParseError).reason).toBe('bad_resolution');
    }
  });

  it('parses 3-element origin with theta=0', () => {
    const text = 'image: a.pgm\nresolution: 0.05\norigin: [-2.0, -1.0, 0.0]\n';
    const m = parseMapYaml(text);
    expect(m.origin).toEqual([-2, -1, 0]);
  });

  it('preserves non-zero theta (caller decides whether to render)', () => {
    const text = 'image: a.pgm\nresolution: 0.05\norigin: [0, 0, 1.5708]\n';
    const m = parseMapYaml(text);
    expect(m.origin[2]).toBeCloseTo(1.5708, 6);
  });

  it('tolerates blank lines and comment-only lines', () => {
    const text =
      '# Generated by slam_toolbox\n' +
      '\n' +
      'image: a.pgm\n' +
      'resolution: 0.05\n' +
      '\n' +
      '# inline comment for origin\n' +
      'origin: [0,0,0]\n';
    const m = parseMapYaml(text);
    expect(m.resolution).toBe(0.05);
    expect(m.origin).toEqual([0, 0, 0]);
  });
});
